#! /bin/sh

D=$(date +"%Y_%m_%d")
DT=$(date +"%m_%d_%Y_%H_%M_%S")

HOMEDIR=/home/pi/dev/cctvmail
MAILFILE=`echo $HOMEDIR/mail$$`
ATTDIR=$HOMEDIR/attachments/$DT
DDIR=$HOMEDIR/attachments/$D

# Create attachments folder
if [ ! -d "$HOMEDIR/attachments" ]; then
    mkdir $HOMEDIR/attachments
fi

# Create results folder
if [ ! -d "$D" ]; then
    mkdir $DDIR
fi

mkdir $ATTDIR
cd $ATTDIR

while read line
do
	echo $line >> $MAILFILE
done

uudeview -i -p $ATTDIR $MAILFILE

rm $MAILFILE

for i in UNKNOWN.*; do j=`echo $i | sed "s/UNKNOWN/$DT/g"`; mv "$i" "$j.jpg"; done

mv *.jpg $DDIR

rm -r $ATTDIR
